name: restaurant_api_dicoding
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  logger: ^2.4.0
  equatable: ^2.0.5
  dio: ^5.5.0+1
  http: ^1.2.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
 uses-material-design: true
 assets:
    - assets/no-internet.png

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
